ITAAcademy/RobotaMolodi

app/Models/Resume.php
resources/views/NewVacancy/newVacancy.blade.php
resources/views/Resume/show.blade.php
resources/views/auth/register.blade.php

Prepair for master

---

resources/views/vacancy/show.blade.php

hot fix for crash on main page

---

app/Http/Controllers/ResumeController.php
app/Http/routes.php
resources/views/Resume/_send_message.blade.php
resources/views/Resume/send_message.blade.php
resources/views/Resume/show.blade.php

I created form a send message

---

resources/views/vacancy/_vacancy.blade.php
resources/views/vacancy/showMyVacancy.blade.php

fexed RM-75( link company)

---

resources/views/Resume/_send_message.blade.php

I fix error item validation

---

resources/views/Resume/_send_message.blade.php

I fix error validation Item

---

app/Http/Controllers/MainController.php
public/css/app.css
resources/views/Resume/_form.blade.php

Bugs 12, bug 45, feature 31

---

app/Http/Controllers/Vacancy/VacancyController.php
app/Models/Vacancy.php
database/migrations/2015_06_09_174158_create_vacancies_table.php
database/seeds/DatabaseSeeder.php
resources/views/NewVacancy/newVacancy.blade.php
resources/views/vacancy/edit.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

add field "Телефон" into  Create, Show and Edit Vacancy

Create,Edit and Show Vacancy with filed "telephone"

---

app/Http/Controllers/Vacancy/VacancyController.php
app/Http/routes.php
resources/views/vacancy/pasteVacancyForm/file.blade.php
resources/views/vacancy/pasteVacancyForm/link.blade.php
resources/views/vacancy/pasteVacancyForm/resume.blade.php
resources/views/vacancy/show.blade.php

Commit e252b21 has mistaken comment. Actual comment is "New feature - response for a vacancy forms are load via AJAX"

Griadchenko a 2

---

app/Http/Controllers/Auth/AuthController.php

Rus,Ukr,Eng names are passing validation during registration,with symbols "-" and "_"

Bug_11 names validation

---

app/Http/Controllers/SearchController.php
app/Http/routes.php
resources/views/app.blade.php

Search feature

---

app/Http/Controllers/SearchController.php
app/Http/Controllers/Vacancy/VacancyController.php

Resolved problem with crash on page 'Create Vacancy' and was added change on search resume\vacancy page

crash on page 'Create Vacancy' 

---

resources/views/Company/_company.blade.php
resources/views/Company/myCompanies.blade.php
resources/views/Resume/myResumes.blade.php
resources/views/vacancy/_vacancy.blade.php
resources/views/vacancy/myVacancies.blade.php

1. Add icons
2. Change buttons: "Створити резюме", "Створити вакансію", "Створити компанію";
3. Change middle views.

Change views in personal cabinet:

---

app/Http/Controllers/SearchController.php
resources/views/main/filter/filterResumes_search.blade.php
resources/views/main/filter/filterVacancies_search.blade.php

Added opportunity to do more difficult search from 'drop menu' after search request

difficult search

---

app/Http/Controllers/MainController.php
app/Http/Controllers/SearchController.php
resources/views/main/filter/ajax.blade.php

was changed drop-menu and search mechanism

Preparing to the change in DB(field 'Уся Україна' )

---

app/Http/Controllers/Company/CompanyController.php
app/Http/Controllers/MainController.php
app/Http/Controllers/SearchController.php
app/Http/routes.php
resources/views/main/filter/company.blade.php
resources/views/main/filter/filterResumes.blade.php
resources/views/main/filter/filterResumes_search.blade.php
resources/views/main/filter/filterVacancies.blade.php
resources/views/main/filter/filterVacancies_search.blade.php
resources/views/main/filter/vacancy.blade.php

Added list of the vacancies after that, when was chosen the company

 list of the vacancies

---

database/seeds/DatabaseSeeder.php

Added data in field 'resumeAllUkraine' and 'vacancyAllUkraine' and deleted filed 'Уся Україна'

deleted filed 'Уся Україна'

---

app/Models/Resume.php
app/Models/Vacancy.php
database/seeds/DatabaseSeeder.php
resources/views/NewVacancy/newVacancy.blade.php
resources/views/Resume/_form.blade.php
resources/views/Resume/edit.blade.php
resources/views/main/filter/resume.blade.php
resources/views/main/filter/vacancy.blade.php
resources/views/vacancy/edit.blade.php

Added field salary min/max during the creating new Vacancy/Resume

 field salary min/max 

---

app/Console/Kernel.php
app/Models/Currency.php
database/migrations/2016_03_08_005907_alter_table_currencies.php

add currency scheduler
add task to cron
* * * * * root php /path/to/artisan schedule:run >> /dev/null 2>&1
such as in my station
* * * * * root php /vagrant/rm/artisan schedule:run >> /dev/null 2>&1

add currency scheduler

---

app/Http/Controllers/Company/CompanyController.php
app/Http/Controllers/MainController.php
resources/views/Company/_company.blade.php
resources/views/main/filter/filterCompanies.blade.php

added opportunity to find lists of vacancy after that when you was chosen Company

lists of vacancy

---

app/Http/Controllers/ResumeController.php
app/Http/Controllers/Vacancy/VacancyController.php
app/Models/Currency.php
app/Models/Resume.php
app/Models/Vacancy.php
resources/views/NewVacancy/newVacancy.blade.php
resources/views/Resume/_form.blade.php
resources/views/Resume/edit.blade.php
resources/views/Resume/myResumes.blade.php
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/app.blade.php
resources/views/main/filter/company.blade.php
resources/views/main/filter/filterCompanies.blade.php
resources/views/main/filter/filterResumes.blade.php
resources/views/main/filter/filterResumes_search.blade.php
resources/views/main/filter/filterVacancies.blade.php
resources/views/main/filter/filterVacancies_search.blade.php
resources/views/main/filter/resume.blade.php
resources/views/main/filter/vacancy.blade.php
resources/views/vacancy/edit.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

pls_commit

---

.gitignore
app/Http/Controllers/ResumeController.php
app/Http/Controllers/UploadFile.php
app/Http/Controllers/Vacancy/VacancyController.php

fix bugs 325, 327, 328
task 330

fix bugs 325, 327, 328

---

app/Http/Controllers/ResumeController.php
app/Http/Controllers/Vacancy/VacancyController.php

fixed crash with search_boolean

search_boolean

---

app/Http/Controllers/UploadFile.php
app/Http/Controllers/Vacancy/VacancyController.php
resources/views/emails/vacancyLink.blade.php
resources/views/vacancy/pasteVacancyForm/file.blade.php
resources/views/vacancy/pasteVacancyForm/link.blade.php
resources/views/vacancy/pasteVacancyForm/resume.blade.php
resources/views/vacancy/show.blade.php

task 339
add modal windows in some views

add modal windows in some views task 339

---

app/Http/Controllers/ResumeController.php
resources/views/Company/show.blade.php
resources/views/vacancy/pasteVacancyForm/file.blade.php
resources/views/vacancy/pasteVacancyForm/link.blade.php
resources/views/vacancy/pasteVacancyForm/resume.blade.php
resources/views/vacancy/show.blade.php

fix bug 360 ,361

---

app/Http/Controllers/MainController.php
app/Http/Controllers/ResumeController.php
app/Http/Controllers/Vacancy/VacancyController.php
app/Http/routes.php
public/js/robotaMolodiUtils.js
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/main/filter/filterResumes.blade.php
resources/views/main/filter/filterVacancies.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

filters are now updated from single r/v

filters_01

---

app/Http/Controllers/Company/CompanyController.php
app/Http/Controllers/ResumeController.php
app/Http/Controllers/Vacancy/VacancyController.php

fix bug 380 381 382 383 384

---

app/Http/Controllers/MainController.php
app/Http/routes.php
resources/views/Company/regCompany.blade.php
resources/views/Resume/_resume.blade.php
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/staticHeaderPages/contacts.blade.php
resources/views/staticHeaderPages/linksContainer.blade.php
resources/views/vacancy/_vacancy.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

bugs and tasks

---

app/Http/Controllers/Company/CompanyController.php

Fix Bug #380

---

app/Http/Controllers/Auth/AuthController.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/ResumeController.php
app/Http/Controllers/Vacancy/VacancyController.php
app/Http/Middleware/Authenticate.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Http/routes.php
app/Models/Resume.php
app/Models/Vacancy.php
public/css/style.css
resources/views/Resume/_form.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/vacancy/edit.blade.php

fix bugs 448 447 416 405 421 420 428

fix bugs 448 447 416 405 421 420 428

---

public/js/robotaMolodiUtils.js
resources/views/app.blade.php
resources/views/main/filter/filterVacancies.blade.php

vilter vacancy by geolocation v1.0

praise geolocation

---

public/css/app.css

.footer {
margin-left: 0;
margin-right: 0;
}

remove horizontal scroll

---

public/css/companies/companiesList.css
public/css/resumes/resumesList.css
resources/views/Company/_company.blade.php
resources/views/Resume/_resume.blade.php
resources/views/main/filter/filterCompanies.blade.php
resources/views/main/filter/filterResumes.blade.php
resources/views/main/filter/filterVacancies.blade.php
resources/views/main/mainContent.blade.php
resources/views/newDesign/company/companiesList.blade.php
resources/views/newDesign/resume/resumesList.blade.php
resources/views/newDesign/topNews.blade.php
resources/views/newDesign/vacancies/topVacancies.blade.php
resources/views/newDesign/vacancies/vacanciesList.blade.php

add oll companiest (list) and oll resume

add listCompaniest

---

public/css/style.css
resources/views/auth/login.blade.php

fixed margin and padding for button "forgot password" and "registration"

Login small fix

---

public/css/cabinet.css
resources/views/Company/myCompanies.blade.php
resources/views/Resume/myResumes.blade.php
resources/views/cabinet/cabinet.blade.php
resources/views/vacancy/myVacancies.blade.php

Newcabinet

---

resources/views/NewVacancy/newVacancy.blade.php
resources/views/Resume/_form.blade.php
resources/views/Resume/create.blade.php

Good news! Now we have select2

Create Select2 for creating

---

resources/views/Company/myCompanies.blade.php
resources/views/NewVacancy/newVacancy.blade.php
resources/views/Resume/_form.blade.php
resources/views/Resume/create.blade.php
resources/views/Resume/myResumes.blade.php
resources/views/footer/footer.blade.php
resources/views/vacancy/myVacancies.blade.php

There is no ajax in cabinet!
Fix bug with footer links. Finished creating new design for all positions "create new ...".

Ajax in cabinet

---

resources/views/auth/leftModal.blade.php
resources/views/staticHeaderPages/contacts.blade.php

Remove "Skype" from all our "Contact" tabs.

Remove Skype

---

resources/views/newDesign/news/includeNews/newsLayout.blade.php

Сторінка "News" була структурно невірно зроблена, тому "Header" невірно відображався . Старий код Кириченка закомітив. Зроблено так щоб інклудились частини сторінки так як на всіх інших.
Task:#2638 - done.

fix news layout

---

app/Http/routes.php
app/Models/City.php
app/Models/Company.php
app/Models/Company_city.php
database/migrations/2017_06_26_205236_create_company_city_table.php
public/css/cabinet/cabinetMyResVacCom.css
resources/views/Company/_company.blade.php
resources/views/Resume/_resume.blade.php
resources/views/vacancy/_vacancy.blade.php

Added to ajax cabinet mycompany.
Fix mistake edit myresume.
Added migrations.
Create pivot table (company_city).

Task#1897 mycompany

---

public/css/myVacancyShow.css
public/css/oneCompany.css
public/css/style.css
public/css/style_resume.css
public/css/vacancyShow.css
resources/views/Resume/_resume.blade.php
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/newDesign/company/show.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

Fix company view

---

public/css/myVacancyShow.css
public/css/oneCompany.css
public/css/style_resume.css
public/css/vacancyShow.css
resources/views/Resume/_resume.blade.php
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/newDesign/company/show.blade.php
resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

Redmine:
Task #2472
Task #2473
Task #2474
And some fixed styles: Company/Resume/Vacancy.

Fix using hypertext in descriptions

---

public/css/myVacancyShow.css
public/css/oneCompany.css
resources/views/newDesign/company/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

Task #3062 Social links for logined users

---

app/Http/Controllers/FilterController.php
app/Models/Company.php
app/Models/Resume.php
app/Models/Vacancy.php
database/migrations/2017_07_05_202442_delete_value_column_from_Rating.php
database/migrations/2017_07_05_202629_add_column_value_typeInt_to_Rating.php
public/css/style.css
resources/views/newDesign/jsForFilter.blade.php
resources/views/newDesign/sortAds/sort.blade.php

Redmine:
Task #1677
Created filtration on ratings
Refactoring

Sort by rating(task#1677)

---

app/Http/Controllers/Admin/NewsController.php
app/Http/Controllers/NewsController.php
app/Http/Controllers/Vacancy/VacancyController.php
resources/views/newDesign/news/includeNews/newsLayout.blade.php
resources/views/newDesign/news/includeNews/newsList.blade.php
resources/views/newDesign/news/includeNews/newsListContent.blade.php

Redmine
Task #3553. New "News" must be place into the head of the: list of "News", topNews, Admin panel "News".
Task #3433. "Топ вакансій" menu, don't close in "Новини" tab.
Task #3434. "Новини" menu, don't close in "Новини" tab.
Task #3480. After re-change information in vacancy tab browser kick user to "Main" cabinet page.

Task #3553

---

app/Http/Controllers/MainController.php
app/Http/Controllers/NewsController.php
app/Models/News.php

Fix last news output and refactor basic news outputting

---

app/Http/Controllers/Vacancy/VacancyController.php
app/Http/routes.php
resources/views/Resume/showMyResume.blade.php
resources/views/newDesign/jsForFilter.blade.php
resources/views/newDesign/search/show.blade.php
resources/views/vacancy/show.blade.php

href="javascript:submit(...)" - dosen't work. in file "resources/views/vacancy/show.blade.php" .  The function expected the form to fill data, most of pages dosen't have the form.  I have decided pass on data to controller without the form. href="javascript:submit(...)" uses in many other files.

redirect to filter from vacancy webpage bug#3741 bug#3771 bug#3772

---

resources/views/auth/formLogin.blade.php
resources/views/footer/footer.blade.php

bug #3707 done

---

public/css/companies/companiesList.css
public/css/resumes/resumesList.css
public/css/vacancies/vacanciesList.css
resources/views/Resume/edit.blade.php
resources/views/app.blade.php
resources/views/auth/leftModal.blade.php
resources/views/footer/footer.blade.php
resources/views/newDesign/admin/news/_form.blade.php
resources/views/newDesign/resume/resumesList.blade.php
resources/views/newDesign/vacancies/vacanciesList.blade.php
resources/views/vacancy/edit.blade.php
resources/views/vacancy/show.blade.php

redmine:
Task#3815
Task#3821 
Task#3830
Task#3774
Task#3738
Task#3844
Task#3708
Task#3763

Fix bugs qa

---

resources/views/header/header.blade.php
resources/views/main/filter/filterCompanies.blade.php
resources/views/main/filter/filterResumes.blade.php
resources/views/main/filter/filterVacancies.blade.php

parselly.css is added by me in previous contribute, but it doesn't use.

add parent blade for companies, resumes, vacancies on main page. 

---

app/Http/Controllers/Company/CompanyController.php
app/Http/Controllers/ResumeController.php
app/Models/Currency.php
app/Models/Industry.php
app/Models/Resume.php
app/Models/User.php
database/migrations/2017_11_16_211231_rename_columns_resumes.php
database/seeds/DatabaseSeeder.php
resources/views/Resume/_resume.blade.php
resources/views/Resume/edit.blade.php
resources/views/Resume/noAccessResume.blade.php
resources/views/Resume/show.blade.php
resources/views/Resume/showMyResume.blade.php
resources/views/Resume/showMyResume.blade.php~
resources/views/newDesign/resume/resumesList.blade.php

fix relationship resume

---

app/Http/routes.php

Class App\Http\Controllers\FilterController does not exist.

FilterController is deleted

---

public/js/closure.js
resources/views/Resume/_resume.blade.php
resources/views/newDesign/vacancies/topVacancies.blade.php
resources/views/vacancy/_vacancy.blade.php

if service is unavailable , it should have class 'unavailable'

fixed incoviniences with using href=#

---

resources/views/Resume/_resume.blade.php

Bug#4137  resolved by specifying target element selector

---

public/js/closure.js
resources/views/vacancy/showMyVacancy.blade.php

closure.js script has been changed, it adds display property "none" to element with class=unavailable now.

closure.js script has been changed

---

app/Filter.php

I forgot to change Filter class, it is changed now

Missed change in filter added

---

app/Http/Controllers/UserController.php
app/Models/User.php
database/migrations/2018_01_25_131832_add_column_avatar_to_users_table.php
resources/views/header/header.blade.php
resources/views/user/edit.blade.php

ability adding avatar is provided to user

---

resources/views/newDesign/company/show.blade.php

Captions "Edit" and "Delete" are changed to corresponding icons from font awesome

Improvement#4293

---

resources/views/vacancy/show.blade.php
resources/views/vacancy/showMyVacancy.blade.php

QA was dissatisfied by hover effect of vacancy title

fixed inconsistencies with clickability of vacancy name

---

resources/views/Resume/show.blade.php
resources/views/app.blade.php
resources/views/newDesign/company/show.blade.php
resources/views/newDesign/seoModule/_meta.blade.php
resources/views/vacancy/show.blade.php

as I was told, I implemented base for SEO module, that is 'description' meta property inside newly added 'seo-module' section in app layout

added description meta property to company, vacancy and resume

---

resources/views/newDesign/socialModule/_index.blade.php
resources/views/newDesign/socialModule/facebook/_meta.blade.php
resources/views/newDesign/socialModule/facebook/set.blade.php
resources/views/newDesign/socialModule/meta.blade.php
resources/views/newDesign/socialModule/twitter/_meta.blade.php
resources/views/newDesign/socialModule/twitter/set.blade.php
resources/views/vacancy/show.blade.php

! IMPORTANT !
Full functionality should be tested on public server to provide crawlers ability to fetch information from source page

added metatags for crawlers and fixed buttons for sharing

---

config/app.php
resources/lang/en/social.php
resources/lang/ua/social.php
resources/views/Resume/show.blade.php
resources/views/newDesign/company/show.blade.php
resources/views/newDesign/seoModule/_meta.blade.php
resources/views/newDesign/socialModule/meta.blade.php
resources/views/newDesign/socialModule/share-btn-block.blade.php
resources/views/vacancy/show.blade.php

added to resumes,companies and vacancies

sharing buttoms using include 

---

app/Http/Controllers/MainController.php
resources/views/newDesign/jsForFilter.blade.php

I hope this is final pull request regarding this issue

fixed resumes lack in filtering

---

resources/views/newDesign/seoModule/_meta.blade.php

!Urgent! fixed cause of failure in _meta

---

app/Http/Controllers/Vacancy/VacancyController.php
app/Http/Requests/SaveResume.php

When user delete own vacancy, thеn opened page of "My vacancyes".

When user delete own vacancy, thеn opened page of My vacancyes

---

app/Http/Composers/SeoMetaTagsComposer.php
app/Providers/ViewComposerServiceProvider.php
config/app.php
resources/views/app.blade.php
resources/views/newDesign/seoModule/index.blade.php

- SeoInfo object is injected in partial with seo meta tags
- SeoInfo object corresponds for page where it being injected

seo meta data

---

database/migrations/2018_02_25_181410_create_seo_infos_table.php
database/migrations/2018_03_03_165649_add_nullable_to_user_service.php

The problem is solved, if the registration time issues appear, there are some related to the fields in the table 'users' with columns 'created_at', 'service', 'access_token', 'refresh_token', 'uuid'

registration_problems

---

app/Models/SeoInfo.php
resources/views/newDesign/admin/seo-module/index.blade.php

keywords will be implemented further

keywords are hidden in model and view

---

resources/views/Company/_company.blade.php
resources/views/Resume/_resume.blade.php
resources/views/vacancy/_vacancy.blade.php
resources/views/vacancy/showMyVacancy.blade.php

Couldn't find JS event "on appear" to hide elements loaded with AJAX therefore they were commented

all "Place in top" buttons are hidden

---

public/css/header.css
resources/views/header/header.blade.php

The menu popped up on the left from the top

The menu popped up on the left from the top

---

resources/views/newDesign/news/includeNews/newsPage.blade.php
resources/views/project/partials/form/_description.blade.php

Improvement #4584 Added the calendar to Project Deadlines

Improvement#4584

---

public/js/animateRightCol.js
resources/views/app.blade.php
resources/views/newDesign/search/show.blade.php
resources/views/newDesign/sliders/byCategory.blade.php
resources/views/newDesign/topNews.blade.php
resources/views/newDesign/vacancies/topVacancies.blade.php

- Animate CSS CND link moved to app layout
- Added classes to content of right column to hide and to animate content
- Added script to show content with delay when page is ready

Animated right content

---

app/Http/Controllers/UploadFile.php
app/Http/routes.php
resources/views/newDesign/admin/news/_form.blade.php
resources/views/newDesign/admin/news/create.blade.php
resources/views/newDesign/admin/news/edit.blade.php

There are a lot of pages use unisharp/ckeditor, my previous changes made a lot of exceptions on pages which use creditor

rolled back changes regarding vendor

---

resources/views/newDesign/layouts/includes/header.blade.php

Admin can not close Adminka in Admin cabinet

commented section Adminka

---

config/mail.php

For sending the link of password reset to e-mail you need to fill .env file.
I ask to add data about
AIL_DRIVER=smtp
MAIL_HOST=?????
MAIL_PORT=?????
MAIL_USERNAME=?????
MAIL_PASSWORD=?????
MAIL_ENCRYPTION=tls

fixed_bug#4810

---

public/css/header.css
resources/views/header/header.blade.php

Adaptive's header does not change visually

Adaptive's header does not change visually

---

resources/views/newDesign/admin/companies/index.blade.php
resources/views/newDesign/admin/industries/index.blade.php
resources/views/newDesign/admin/news/index.blade.php
resources/views/newDesign/admin/resumes/index.blade.php
resources/views/newDesign/admin/seo-module/index.blade.php
resources/views/newDesign/admin/sliders/index.blade.php
resources/views/newDesign/admin/sliders/show.blade.php
resources/views/newDesign/admin/users/index.blade.php
resources/views/newDesign/admin/vacancies/index.blade.php
resources/views/newDesign/layouts/admin.blade.php
resources/views/newDesign/layouts/includes/columnLeft.blade.php
resources/views/newDesign/layouts/includes/head.blade.php

- refactored views 
- add confirmation

Task#5026-5030

---

public/css/header.css
resources/views/header/header.blade.php

New footer

---

app/Models/Project.php
database/migrations/2018_04_19_130427_add_column_location_city_to_table_projects.php
resources/views/project/partials/_project.blade.php
resources/views/project/partials/form/_description.blade.php

- added migration to create column 'location_city';
- added property 'location_city' to Project model;
- added validation rule for 'location_city' property to Project model;
- simple changes in views to make one work properly with validation of 'location_city' property;
- simple improvements in show view of project entity

Bug#ProjectsCity

---

public/css/news.css
resources/views/newDesign/admin/aboutUs/index.blade.php
resources/views/newDesign/admin/companies/index.blade.php
resources/views/newDesign/admin/industries/_form.blade.php
resources/views/newDesign/admin/industries/create.blade.php
resources/views/newDesign/admin/industries/edit.blade.php
resources/views/newDesign/admin/industries/index.blade.php
resources/views/newDesign/admin/news/edit.blade.php
resources/views/newDesign/admin/news/index.blade.php
resources/views/newDesign/admin/news/one.blade.php
resources/views/newDesign/admin/resumes/index.blade.php
resources/views/newDesign/admin/seo-module/_form.blade.php
resources/views/newDesign/admin/seo-module/create.blade.php
resources/views/newDesign/admin/seo-module/edit.blade.php
resources/views/newDesign/admin/seo-module/index.blade.php
resources/views/newDesign/admin/users/index.blade.php
resources/views/newDesign/admin/vacancies/index.blade.php
resources/views/newDesign/layouts/admin.blade.php

Я отступы в коде не трогала и не форматировала, по-видимому, это пхпШторм сам, так что сильно не бить ))

small changes

---

additional_readme.txt
database/migrations/2018_03_03_165649_add_nullable_to_user_service.php
public/css/vacancies/topVacancies.css
resources/views/main/filter.blade.php
resources/views/main/filters.blade.php
resources/views/main/index.blade.php
resources/views/newDesign/sortAds/sort.blade.php

fixed first paje mobile view

---

resources/views/vacancy/show.blade.php

fixed vacancy mobile view

---

public/css/news.css
resources/views/newDesign/admin/aboutUs/create.blade.php
resources/views/newDesign/admin/aboutUs/edit.blade.php
resources/views/newDesign/admin/news/create.blade.php
resources/views/newDesign/admin/news/edit.blade.php
resources/views/newDesign/admin/news/index.blade.php
resources/views/newDesign/admin/news/one.blade.php
resources/views/newDesign/layouts/includes/columnLeft.blade.php

small corrections in the admin

Admin news short description

---

app/Http/Controllers/Admin/NewsController.php
resources/views/newDesign/admin/news/_form.blade.php
resources/views/newDesign/admin/news/create.blade.php
resources/views/newDesign/admin/news/index.blade.php

fixing published news, second time

---

public/css/oneCompany.css
resources/views/newDesign/company/show.blade.php

fixed mobile view (company/create) page

Company-Page-change-view-and-mobile-view

---

public/css/paginator/paginator.css
resources/views/newDesign/news/includeNews/newsListContent.blade.php

fix pagination (mobile)

---

public/rm-styles.css
resources/views/NewVacancy/users.blade.php

fixed mobile view (company/create) page

fixed mobile view (company/create) page

---

app/Consult.php
app/User.php
database/migrations/2018_07_05_161634_add_nullable_to_vacancies_telephone.php
database/migrations/2018_07_05_161815_create_consults_table.php

added row telephone(nullable) in table 'users'
added table consults

added table consults

---

config/mail.php

add env mail parameters

---

app/Http/Controllers/Vacancy/ResponseController.php
public/js/validateFile.js
resources/views/vacancy/show.blade.php

There is on server needed to change in php.ini values:
**upload_max_filesize = 50M
post_max_size = 100M
max_execution_time = 600**
To find php.ini location just run in console or terminal **php --ini**

Attach file error
